### ISSUE TITLE
Adding base and related tables to gpkg_extensions

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage-related-tables#36]
The extension currently requires adding rows for `gpkgext_relations` and the mapping table(s) to the `gpkg_extensions` table.

There is a case where a non-conforming ("never heard of related tables extension") client can cause interop problems - UPDATE or DELETE of a row in the base table or related table. Imagine your client deletes a row in the related table - now you have a row in the mapping table where the target primary key doesn't exist. Unfortunate.

If it is was just DELETE, we could do a trigger that causes (potentially cascading) DELETEs through the geopackage. That might be surprising though, and would not always be the right thing to do for an UPDATE. 

I think we need to add the base table and related table to `gpkg_extensions` with a scope of `write-only`.

**Comment by tabinfl** [comment]
If we’re not requiring FK constraints, it would be up to the RTE implementor to deal with unexpected disappearance/alteration of base table rows, I’d think.

**Comment by jyutzler** [comment]
We can discuss this on Monday. It might be a good topic for the ER.

**Comment by jyutzler** [comment]
This does not appear to be actionable at  this time. We will put something in the ER. (See https://github.com/opengeospatial/gpkg-rte-ie-er/issues/9).
