### ISSUE TITLE
ATS for Requirement 4 - PRAGMA does not show UNIQUE constraint, only PK

### ISSUE THREAD

**Issue by tabinfl** [opengeospatial/geopackage-related-tables#51]
```
1. PRAGMA table_info(gpkgext_relations) 
[...]
3. Pass if the column names, types, nullability, default values,
primary key, and unique key constraints match all of those in
the contents of [gpkgext_relations_table].
```

The PRAGMA query return data allows checking everything but the UNIQUE constraint on the mapping_table_name field.

could add
```
PRAGMA index_list(gpkgext_relations);
```
to check for unique = 1 and then
```
PRAGMA index_info({index_name});
```
to verify that it's on the correct (mapping_table_name) column.

There may be an easier way, I keep running into sqlite's limited SQL.

**Comment by bradh** [comment]
I think this is the only way - there is code that does something similar in the ETS core.

**Comment by jyutzler** [comment]
I think @bradh is referring to https://github.com/opengeospatial/ets-gpkg12/blob/master/src/main/java/org/opengis/cite/gpkg12/CommonFixture.java#L243.

**Comment by jyutzler** [comment]
moved to :point_up:
