### ISSUE TITLE
Define relationship cardinality

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-related-tables#59]
The current draft does not provide an explicit way to define the cardinality of a relationship (many-to-many, one-to-many, or many-to-one). This potentially affects how the relationship could be exported into another data store. In the event that this detail is important, the schema and/or metadata extensions could be used but the details have not been worked out yet.

**Comment by bradh** [comment]
We discussed this during development, and there are other cases (up to 5, must be an even number, etc). Its possible to identify what the current cardinality is, although that may not represent the intended cardinality.  Do we have a specific use case or advocate who needs this information?

**Comment by jyutzler** [comment]
moved to :point_up:
