### ISSUE TITLE
Add a profile to handle external references

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-related-tables#60]
We don't currently have a way to deal with relationships between base data and related data that lives outside the GeoPackage. In theory this could be supported through a URI, but the details of doing this have not been specified.

**Comment by bradh** [comment]
This would be fairly easy to do, but this isn't a great fit for GeoPackage, which is better suited to offline use, and avoiding dependence on a particular network. 

Do we have a specific use case that needs this? Is there an advocate for the requirement?

**Comment by jyutzler** [comment]
moved to :point_up:
