### ISSUE TITLE
Provide guidance on avoiding data duplication

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-related-tables#62]
Since related tables support arbitrary fields, an attributes table containing media could have a hash column that would allow a client to check whether a particular piece of media is present in the table before adding it again. This would be informative text.

**Comment by bradh** [comment]
While it could, this might be better done as an application-specific addition, rather than as the core spec. My concern is that it could become out-of-sync with the actual data. Perhaps it could be noted as a possibility rather than codifying any particular normative or informative practice.

**Comment by jyutzler** [comment]
Yes, this is what I mean by informative text. I think we're in agreement here.

**Comment by jyutzler** [comment]
This was added to the [getting started guide](https://github.com/opengeospatial/geopackage-related-tables/wiki/Getting-Started#media).
