### ISSUE TITLE
Add option for vector tiles + attributes

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-related-tables#63]
As part of the Vector Tiles Pilot, we have identified the need for a new requirements class for the Related Tables Extension. The use case is that you have vector tiles which may contain attributes in addition to geometries. However, once you enter GeoPackage land, you would prefer to have the attributes in an attributes table so that you can query on them without breaking open the individual tiles. Since features can be strewn across many tiles, there is a many-to-many relationship between attributes and tiles. Therefore I am going to propose a new requirements class for the RTE to map tiles and attributes. I propose a `relation_name` of `vector_tiles_attributes`. This would become Section 7.5 of the RTE.

**Comment by bradh** [comment]
I'm good with the conceptual need and solution.

However I'm not sure I see how this is going to work in a spec management sense. Does RTE now have a dependency on the vector tiles extension? Would it make more sense to make that part / profile of vector tiles depend on "RTE core" and treat this `relation_name` as part of the vector tiles extension?

**Comment by jyutzler** [comment]
Excellent question and the short answer is that I do not know at this time. I'll think about it.

**Comment by tabinfl** [comment]
Perhaps we could add a note that `relation_name` must begin with x- unless part of an OGC-adopted standard or extension. The other extension would then be responsible for specifying details of that relationship.
